{{- if .Values.policy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "bitcoin.fullname" . }}
  labels:
    app: {{ template "bitcoin.name" . }}
    chart: {{ template "bitcoin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "bitcoin.fullname" . }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.110.103/32
{{- end }}